POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###
GET http://127.0.0.1:4000/protected HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc1NTAwODk2NH0.g8lu-_WR8xaKcXmExLjzdbJvl1AFvq57qxwztx7DEPfz4_xSm-wEHtNfgOj5Y0fxkXKwGNMB1dMt2BmkxXvKPQ

###

GET http://127.0.0.1:4000/protected HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTc1NTAwODk5MH0.53nnQK9rvfK3EfERqeTIqfJdCilr1R6tTi2zPqOUUJHxjheqbtQBIfhNWmY0inaLcxl9QBsDBh3LjR-EywgisQ

###
GET http://127.0.0.1:4000/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc1NTAwODk2NH0.g8lu-_WR8xaKcXmExLjzdbJvl1AFvq57qxwztx7DEPfz4_xSm-wEHtNfgOj5Y0fxkXKwGNMB1dMt2BmkxXvKPQ

###

GET http://127.0.0.1:4000/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTc1NTAwODk5MH0.53nnQK9rvfK3EfERqeTIqfJdCilr1R6tTi2zPqOUUJHxjheqbtQBIfhNWmY0inaLcxl9QBsDBh3LjR-EywgisQ