[package]
name = "user_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"

[dev-dependencies]
tempfile = "3.0"
